import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoutButton } from "./LogoutButton";
import { TimezoneSetter } from "./TimezoneSetter";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	robots: {
		index: false,
		follow: false,
		googleBot: {
			index: false,
			follow: false,
			noimageindex: true,
			"max-video-preview": -1,
			"max-image-preview": "none",
			"max-snippet": -1,
		},
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.png" type="image/svg+xml"></link>
				<meta name="robots" content="noindex, nofollow, noai, noimageai" />
				<meta name="googlebot" content="noindex, nofollow, noai, noimageai" />
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<TimezoneSetter />
				{children}
			</body>
		</html>
	);
}
